deployment:
  replicas: 1

service:
  type: NodePort
ingressRoute:
  dashboard:
    enabled: true

api:
  dashboard: true
  insecure: true # lab

ports:
  traefik:
    port: 8080
    expose:
      default: true
    exposedPort: 8080
    nodePort: 30900

logs:
  level: INFO
