deployment:
  replicas: 1

service:
  type: NodePort
  nodePorts:
    http: 30080
    https: 30443

ingressRoute:
  dashboard:
    enabled: true

api:
  dashboard: true
  insecure: true # lab

logs:
  general:
    level: INFO
